### ISSUE TITLE
Grammar ambiguous/hangs as of v2.7.12

### ISSUE THREAD

**Issue by trevorr** [Hardmath123/nearley#176] opened 2017-02-24 13:56 UTC
nearley 2.7.12, particularly commit 3b415764680df370317f1de3519bf45263a3b5fa (fix leo bug, #159), causes a [grammar](https://github.com/affinipay/virtsecgroup/blob/master/src/grammar.ne) that had been working (without ambiguity) to become ambiguous or run out of memory, depending on the input size. Perhaps the bug is in the grammar, but I'm not sure how to determine that. It seems to be around the whitespace/separator handling (which explains the rapid explosion of combinations), but I haven't been able to spot the ambiguity. Any debugging tips or insight into the nature of the #159 fix would be greatly appreciated.

Reproducing:

```
$ git clone https://github.com/affinipay/virtsecgroup.git
$ cd virtsecgroup
$ npm i
$ ./node_modules/.bin/babel-node lib/index.js < examples/inherit_source1.vsg
<valid output>
$ sed -ie 's/"nearley": "=2.7.11"/"nearley": "=2.7.12"/' package.json
$ npm i
$ ./node_modules/.bin/babel-node lib/index.js < examples/inherit_source1.vsg
<AST dump>
Error: Ambiguous parse: got 8 results
```

**Comment by tjvr** [comment] 2017-02-24 14:07
@trevorr Would you be able to verify whether #171 solves your issue? :)

**Comment by trevorr** [comment] 2017-02-24 15:11
@tjvr I pulled your branch, but the result is the same as 2.7.12.

**Comment by Hardmath123** [comment] 2017-02-24 15:39
The #159 fix fixed a bug where certain parsings were ignored. That meant that ambiguous grammars *seemed* unambiguous because some of the ambiguous parsings got ignored.

Your grammar is indeed ambiguous on whitespace. Try replacing line 68 (https://github.com/affinipay/virtsecgroup/blob/master/src/grammar.ne#L68) with `ws -> [\f\r\t\v\u00A0\u2028\u2029 ] {% (d, l) => new ast.Whitespace(makeloc(l), d[0].join('')) %}` (no `:+`). That should fix the whitespace problem.

The issue is that you have essentially `__ -> ws:+` and `ws -> [\f\r\r…]:+`, so parsing a string many whitespace characters (such as `•••`) can happen many, many ways (such as `(•)(•)(•)` or `(••)(•)` or `(•)(••)` or `(•••)`). I hope this helps.

**Comment by trevorr** [comment] 2017-02-24 16:20
@Hardmath123 Thanks so much, that does fix the parsing issue! It seems so obvious now. 😉 

I had that `:+` there to merge consecutive (non-comment) whitespace into a single AST node (though I don't ultimately keep that node currently). Is there a general technique/transformation I could use to make the whitespace rule "greedy"/longest-match? This is my first attempt at using a scanner-less parser generator after years of scanners.

**Comment by Hardmath123** [comment] 2017-02-24 16:21
Why do you want to keep whitespace in your AST at all?

**Comment by trevorr** [comment] 2017-02-24 16:26
I was considering preserving comments and possibly whitespace for future features such as documentation generation or code formatting (where existing whitespace could be used as a hint for preserving some stylistic aspects).

**Comment by Hardmath123** [comment] 2017-02-24 16:29
Ah. You can get away by storing the `location` (second argument to a postprocessor) for each *actual* AST node — this should give you enough information to do cool formatting-ey things.

(I'm closing this issue for now because it is fixed. But feel free to ask questions if you have any!)

**Closed by Hardmath123** 2017-02-24 16:29 UTC
