### ISSUE TITLE
Request: Live parser playground

### ISSUE THREAD

**Issue by matthew-dean** [Hardmath123/nearley#106] opened 2016-07-04 04:45 UTC
Would it be possible to set up a page like http://pegjs.org/online as a way to learn how to make grammar for Nearley?

(Double bonus: suggested optimizations.)

**Comment by Hardmath123** [comment] 2016-07-04 05:49
Sure, we used to have a demo but it was a bit glitchy. Does anyone want to take the lead on implementing this? It should be easy-peasy.

**Comment by Hardmath123** [comment] 2016-07-04 05:53
Duplicate of #37, #68.

**Comment by Hardmath123** [comment] 2016-07-04 06:15
(Last update for tonight: see `index.html` and `www/main.js` for existing progress on this. Really, all that's left is for someone to hack together a frontend with some sort of text box and a couple of buttons.)

**Comment by matthew-dean** [comment] 2016-07-04 06:54
Ah.

**Comment by Hardmath123** [comment] 2017-02-17 01:09
See http://omrelli.ug/nearley-playground/.

**Closed by Hardmath123** 2017-02-17 01:09 UTC
Labels: duplicate, enhancement, up for grabs (help wanted)
