### ISSUE TITLE
Grammar brings nearley to an infinite loop

### ISSUE THREAD

**Issue by erezsh** [Hardmath123/nearley#167] opened 2017-02-17 22:14 UTC
Nearley never terminates when running with the input "a", and the following grammar: 
> start -> a
> a -> a | "a"

Of course the grammar is badly formed, but since nearley aspires to parse "any grammar", perhaps an error is a more appropriate behavior?
Full detection might be tricky due to empty rules, but it shouldn't be impossible, as far as I can tell. 

Anyway, I thought it's worth an issue.

**Comment by Hardmath123** [comment] 2017-02-18 01:23
Definitely a bug: nearley should never go into an infinite loop. I'm pretty sure it's the Leo optimization; I will investigate. Thanks for reporting.

**Comment by erezsh** [comment] 2017-02-18 14:42
Check out http://loup-vaillant.fr/tutorials/earley-parsing/parser
Read the section called "One last trap"
I believe it describes the bug, and if so, a way to solve it.
I might write such a solution myself if you don't beat me to it :)

**Comment by tjvr** [comment] 2017-02-18 14:46
Ugh.

The easiest way to fix this afaik is to switch to an SPPF-style structure, which I want to do anyway: #163. But that has it's own problems (specifically, it makes it harder to support predicates).

I would hold off on sending PRs; I'm currently reworking the internals anyway. :-)

**Comment by tjvr** [comment] 2017-02-24 15:50
Can confirm: my SPPF-style Earley parser can handle this. (Or my parser has a bug and doesn't output all the derivations, which is possible. But it _should_ work.)

The key thing here is to merge duplicate states a la #22. I'm not sure if this requires SPPF but I think it does.

---

Loup's suggestion is instead to detect the problem as it happens:

> such bottomless grammars are bogus, and should be rejected. Fortunately, unlike unlike ambiguous grammars, they can be detected with a little bit of static analysis.

We could do this in current nearley I suppose? But if we're switching to SPPF anyway then I don't see the point! :-)

**Comment by kdex** [comment] 2017-03-08 15:16
Here's a grammar where no BNF clause matches the left-hand side, so this should be well-formed. It also results in an infinite loop, though:

```
Main -> Expression
Expression ->
	_ Expression _
	| "(" Expression ")"
	| [0-9]:+
_ -> [\s]:*
```

Is there a current workaround?

**Comment by tjvr** [comment] 2017-03-08 15:18
I think this is bogus under Loup's definition. Since _ is nullable, you have the production Expression -> Expression.

**Comment by erezsh** [comment] 2017-03-08 15:26
@tjvr , what do you mean when you say SPPF will make it harder to support predicates? What kind of predicates, and why would it be harder?

**Comment by kdex** [comment] 2017-03-08 15:59
Not sure if this approach always works, but at least for context-free grammars, resolving a recursion loop over a production of the form `A -> A` should be fairly doable.

Consider the BNF:

```
S → A
A → A | B | C_1 | C_2 | … | C_n
B → A
```

It contains the productions `A → A` and `A → B → A`. Both of which are bogus. This can be resolved like so:

1) Create a new (empty) rule for `D`.
2) If there is a rule in that contains a looping derivation (e.g. `A → A`, `A → B → A`), substitute the last derivation in the chain of the form `X → A` by `X → D`. So in this example, `A → A` becomes `A → D` and `B → A` becomes `B → D`. All non-looping clauses in the affected rules are then removed.
3) Add all removed non-looping clauses to `D`.

The resulting production rules of the new grammar will have the form:

```
S → A
A → D | B
B → D
D → C_1 | C_2 | … | C_n
```

As you can see above, the new grammar might become ambiguous, but maybe there's other magic that can be done to prevent that.

**Comment by erezsh** [comment] 2017-03-08 16:20
That's an interesting approach. Why not just forbid such a grammar?

**Comment by kdex** [comment] 2017-03-08 16:36
Because a whole infinity of grammars can be fixed, even without ambiguity. The grammar from above would be a good candidate. The outlined approach yields an unambiguous grammar and fixes it:

```
Main -> WExpression
WExpression ->
	Expression
	| _ Expression _
Expression ->
	"(" Expression ")"
	| [0-9]:+
_ -> [\s]:*
```
Unfortunately, the approach only works for a subset of grammars (I think only those whose infinite loops are caused by nullability). 

For your grammar, the approach *will* fix the infinite loop, but the result will have different semantics:

```
start -> a
a -> b
b -> "a"
```

**Comment by kdex** [comment] 2017-03-08 16:43
(I'm *not* saying the approach is perfect, *nor* that nearly should use it. I really just wanted to document a workaround that might work for some.)

**Comment by erezsh** [comment] 2017-03-08 16:44
Interesting. A SPPF parser would return something that is analogous to:
`
start -> a | "a"
a -> b
b -> "a"
`
(if b is later removed from the parse tree of course)

**Comment by Hardmath123** [comment] 2017-03-09 01:28
Tim, I feel even though that grammar is bogus by Loup's definition we should support parsing it without blowing up. That's a "reasonable" enough thing that I can see it being an issue.

**Closed** 2017-05-29 10:33 UTC
Labels: bug
