### ISSUE TITLE
parser.results is an empty list

### ISSUE THREAD

**Issue by solo989** [Hardmath123/nearley#253] opened 2017-07-29 00:21 UTC
When I feed my parser a valid statement it does not fail but it also doesn't put the results in parser.results.
I looked through nearly.js and the problem seems to be that it cant find data with t.rule.name that matches start in the Parser.prototype.finish function. Somewhere along the way its not finishing all the postprocessing would be my best guess.
I've been using the latest version of nearly plus nearly-moo and moo for tokenizing.
Attached are the files I've been working with.
[grammar.zip](https://github.com/Hardmath123/nearley/files/1184504/grammar.zip)
Interestingly enough if you remove simple_block_one_line from grammar.ne and redirect main to something else the grammar should work.

On another note there have been cases where my parser refuses to run particular postprocessing funcs.
If you add a func to defname in grammar.ne it shouldn't run. Maybe the two problems are related.

**Comment by tjvr** [comment] 2017-07-29 08:35
If results is empty, that’s not a bug in Nearley—it means it couldn’t parse your input! Check your grammar and your input: you’ll have a mistake somewhere. :-)

**Comment by solo989** [comment] 2017-07-29 12:12
As far as I can tell my program returns an empty list when the parser is fed a newline character at the end of a string. 
Is this a bug that's going to be addressed or should I get used to dropping any trailing newline characters? Are there any other states that you know of that will return an empty list instead of a syntax error?

**Comment by deltaidea** [comment] 2017-07-29 16:39
Again, this is not a bug. `parser.results` will be empty if there's no way to parse the text, with or without syntax errors. That usually means an unexpected end of input.
Do you think this should lead to an exception? I'm not sure.

I see a couple sneaky issues in the grammar you provided:

- `varname -> ... | ... {% %}` - the postprocessor here only works when the option on the right of `|` is matched. This allows to specify different postprocessors for different variations of the same thing. To apply the same postprocessor, wrap the whole thing in `(... | ...)` and then do `d = d[0]` or something like that to unwrap.
- Your lexer `indented(moo.compile(tokens))` swallows single `\n`. E.g. `sign\n` gives a single token `type: 'name', value: 'sigh'`. I'm not sure why is that. If you feed `sigh\n\n` everything works. Additionally, rule `simple_block_one_line` has a required `newline` at the end. Therefore, with a single `\n` the `simple_block_one_line` rule doesn't apply and there's no other way to parse the input. But there's no syntax error, it's just that no rules match the input.

**Comment by Hardmath123** [comment] 2017-07-29 18:07
> Thanks for providing the example! I wish everyone would do that.

Wanted to second this. I agree with Tim and @deltaidea that it's not quite a nearley bug, but nevertheless thanks for providing enough details for us to take a look. :-)

By the way, postprocessor issues are usually unrelated to does-it-parse issues, unless you are using the `reject` feature.

**Comment by Hardmath123** [comment] 2017-07-29 18:10
> I'll open a PR and work on the docs for a bit.

If you're working on the docs, you might want to start by documenting lexers! See #248 and Tim's work there for a starting point.

**Comment by solo989** [comment] 2017-07-29 22:44
Thanks for the help. 
I think I saw the multiple post processing funcs attached to one statement then subsequently forgot about it. Maybe if this was a documented feature on the front page or more examples used it I wouldn't have made this mistake.
I will definitely take another look at my custom tokenizer to see if any strangeness is going on.

**Comment by tjvr** [comment] 2017-08-07 21:50
I'm going to close this for now. Let us know if you have any other issues! :-)

**Closed by tjvr** 2017-08-07 21:50 UTC
Labels: question
