### ISSUE TITLE
json.ne example throwing errors - Issue with moo?

### ISSUE THREAD

**Issue by snalld** [Hardmath123/nearley#257] opened 2017-08-03 10:36 UTC
I’m trying to run the example json.ne grammar on the following input:

`["hello”]`

And getting the following error:

```
Error: invalid syntax at line 1 col 2:

  ["hello"]
   ^
Unexpected "\”"
```

Am I missing something?

Just for context I’ve written a couple of simple grammars before without using moo or a custom lexer without any trouble. It seems from the nearley docs that there’s been a lot of change with the lexer implementation recently, so I’m thinking I may have missed something... 

I'm running nearley 2.10.2 and moo 0.4.0

**Comment by deltaidea** [comment] 2017-08-03 10:38
`Unexpected "\”"` - are you sure you're feeding `"` and not `”`?

**Comment by snalld** [comment] 2017-08-03 10:41
Yeah I'm sure. But also if I run it on:
```
[
  "hello"
]
```
I get the following error:

```
Error: invalid syntax at line 2 col 0:

    "hello"
  ^
Unexpected "\n"
```

So I dont think it has to do with the input

**Comment by snalld** [comment] 2017-08-03 10:44
Seems to be an issue with tokens longer than 1 char..?

`'[': '[',` works fine, but `space: {match: /\s+/, lineBreaks: true},` seems to be throwing?

**Comment by snalld** [comment] 2017-08-03 10:46
also just tested it with `[]` and it passes but `[]\n` (as in a trailing new line) throws

**Comment by snalld** [comment] 2017-08-03 11:11
I've just tested the same json lexer directly with moo and it doesn't throw any errors.

Any thoughts  @deltaidea @tjvr?

**Comment by deltaidea** [comment] 2017-08-03 11:29
> just tested the same json lexer directly with moo

Right, if you run it without Moo, it won't work because it expects tokens `[`, `%value`, ... and instead gets tokens `[`, `"`, ...
The built-in lexer doesn't know about the types of custom tokens (`%token`) that you tell Moo about.

This error can be easily distinguished: `Unexpected "\”"` - notice that the unexpected token is a string and not an object. Moo gives you object, so the error would be `Unexpected {type: "string", value: ...}`

**Comment by snalld** [comment] 2017-08-04 03:56
> are you sure you're feeding " and not ”?

Yeah I'm sure haha, not sure why it's coming up with that output. Also this input is erroring too `[0]` so I don't think it's specifically about the "s
```
Error: invalid syntax at line 1 col 2:

  [0]
   ^
Unexpected "0"
```

Happy to share my code. What's the best way to do that? Attach files?

**Comment by snalld** [comment] 2017-08-04 04:37
Here's my files. I'm using the example json.ne but I've included it anyway. Thanks in advance!


[nearley-json-grammar.zip](https://github.com/Hardmath123/nearley/files/1199238/nearley-json-grammar.zip)

**Comment by deltaidea** [comment] 2017-08-04 05:16
Duplicate of #247. Solution:

```diff
  var grammar = require('./json.js')
- var p = new nearley.Parser(grammar.ParserRules, grammar.ParserStart);
+ var p = new nearley.Parser(nearley.Grammar.fromCompiled(grammar));

  console.log(grammar.Lexer.has('number'))
```

Docs currently don't mention `fromCompiled()` properly. We're working on that. Check out [this preview of updated docs](https://github.com/deltaidea/nearley/blob/improve-docs/README.md).

Thank you for the repro code! You're awesome.

**Comment by snalld** [comment] 2017-08-04 05:21
Oh sorry, I went through some of those issues but didn't see that bit haha.

Thanks @deltaidea!! 

Let me know if there's anything I can do to help write the new docs or anything else. Keen to get involved!

**Comment by tjvr** [comment] 2017-08-04 07:32
Glad we solved it :-)

Want to help review @deltaidea's docs PR? :-)

**Closed by tjvr** 2017-08-04 07:33 UTC
Labels: question
